INSERT INTO majors (name) VALUES ('Accounting Certificate');
INSERT INTO majors (name) VALUES ('African Cultural Studies BA');
INSERT INTO majors (name) VALUES ('African Cultural Studies BS');
INSERT INTO majors (name) VALUES ('African Studies Certificate');
INSERT INTO majors (name) VALUES ('Afro-American Studies BA');
INSERT INTO majors (name) VALUES ('Afro-American Studies BS');
INSERT INTO majors (name) VALUES ('Afro-American Studies Certificate');
INSERT INTO majors (name) VALUES ('Agricultural and Applied Economics BS');
INSERT INTO majors (name) VALUES ('Agricultural Business Management BS');
INSERT INTO majors (name) VALUES ('Agronomy BS');
INSERT INTO majors (name) VALUES ('American Indian Studies Certificate');
INSERT INTO majors (name) VALUES ('Animal Sciences BS');
INSERT INTO majors (name) VALUES ('Anthropology BA');
INSERT INTO majors (name) VALUES ('Anthropology BS');
INSERT INTO majors (name) VALUES ('Applied Mathematics, Engineering, and Physics BS');
INSERT INTO majors (name) VALUES ('Applied Social Science, BLS ');
INSERT INTO majors (name) VALUES ('Archaeology Certificate');
INSERT INTO majors (name) VALUES ('Art BS');
INSERT INTO majors (name) VALUES ('Art BFA');
INSERT INTO majors (name) VALUES ('Art Education BS');
INSERT INTO majors (name) VALUES ('Art History BA');
INSERT INTO majors (name) VALUES ('Art History BS');
INSERT INTO majors (name) VALUES ('Art History Certificate');
INSERT INTO majors (name) VALUES ('Art Studio Certificate');
INSERT INTO majors (name) VALUES ('Arts and Teaching Certificate');
INSERT INTO majors (name) VALUES ('Asian American Studies Certificate');
INSERT INTO majors (name) VALUES ('Asian Languages and Cultures BA');
INSERT INTO majors (name) VALUES ('Asian Languages and Cultures BS');
INSERT INTO majors (name) VALUES ('Astronomy–Physics BA');
INSERT INTO majors (name) VALUES ('Astronomy–Physics BS');
INSERT INTO majors (name) VALUES ('Athletic Healthcare Certificate');
INSERT INTO majors (name) VALUES ('Atmospheric and Oceanic Sciences BA');
INSERT INTO majors (name) VALUES ('Atmospheric and Oceanic Sciences BS');
INSERT INTO majors (name) VALUES ('Biochemistry (L&S) BA');
INSERT INTO majors (name) VALUES ('Biochemistry (CALS) BS');
INSERT INTO majors (name) VALUES ('Biochemistry (L&S) BS');
INSERT INTO majors (name) VALUES ('Biological Systems Engineering BS');
INSERT INTO majors (name) VALUES ('Biology (L&S) BA');
INSERT INTO majors (name) VALUES ('Biology (CALS) BS');
INSERT INTO majors (name) VALUES ('Biology (L&S) BS');
INSERT INTO majors (name) VALUES ('Biology Core Curriculum Honors Certificate');
INSERT INTO majors (name) VALUES ('Biology in Engineering for Engineering Majors Certificate');
INSERT INTO majors (name) VALUES ('Biomedical Engineering BS');
INSERT INTO majors (name) VALUES ('Botany BA');
INSERT INTO majors (name) VALUES ('Botany BS');
INSERT INTO majors (name) VALUES ('Business Certificate');
INSERT INTO majors (name) VALUES ('Business Administration-Human Resources BBA');
INSERT INTO majors (name) VALUES ('Business Administration-Management BBA');
INSERT INTO majors (name) VALUES ('Business Administration-Marketing BBA');
INSERT INTO majors (name) VALUES ('Business Management for Agricultural and Life Sciences Certificate');
INSERT INTO majors (name) VALUES ('Business: Accounting BBA');
INSERT INTO majors (name) VALUES ('Business: Actuarial Science BBA');
INSERT INTO majors (name) VALUES ('Business: Finance, Investment, and Banking BBA');
INSERT INTO majors (name) VALUES ('Business: Information Systems BBA');
INSERT INTO majors (name) VALUES ('Business: Management and Human Resources BBA');
INSERT INTO majors (name) VALUES ('Business: Marketing BBA');
INSERT INTO majors (name) VALUES ('Business: Operations and Technology Management BBA');
INSERT INTO majors (name) VALUES ('Business: Real Estate and Urban Land Economics BBA');
INSERT INTO majors (name) VALUES ('Business: Risk Management and Insurance BBA');
INSERT INTO majors (name) VALUES ('Business: Supply Chain Management BBA');
INSERT INTO majors (name) VALUES ('Cartography and Geographic Information Systems BA');
INSERT INTO majors (name) VALUES ('Cartography and Geographic Information Systems BS');
INSERT INTO majors (name) VALUES ('Chemical Engineering BS');
INSERT INTO majors (name) VALUES ('Chemistry BA');
INSERT INTO majors (name) VALUES ('Chemistry BS');
INSERT INTO majors (name) VALUES ('Chicana/o and Latina/o Studies Certificate');
INSERT INTO majors (name) VALUES ('Chinese BA');
INSERT INTO majors (name) VALUES ('Chinese BS');
INSERT INTO majors (name) VALUES ('Chinese BSE');
INSERT INTO majors (name) VALUES ('Chinese Professional Communication Certificate');
INSERT INTO majors (name) VALUES ('Civil Engineering BS');
INSERT INTO majors (name) VALUES ('Classical Humanities BA');
INSERT INTO majors (name) VALUES ('Classical Humanities BS');
INSERT INTO majors (name) VALUES ('Classical Studies Certificate');
INSERT INTO majors (name) VALUES ('Classics BA');
INSERT INTO majors (name) VALUES ('Classics BS');
INSERT INTO majors (name) VALUES ('Communication Arts BA');
INSERT INTO majors (name) VALUES ('Communication Arts BS');
INSERT INTO majors (name) VALUES ('Communication Sciences and Disorders BA');
INSERT INTO majors (name) VALUES ('Communication Sciences and Disorders BS');
INSERT INTO majors (name) VALUES ('Communication Sciences and Disorders BSE');
INSERT INTO majors (name) VALUES ('Community and Environmental Sociology BS');
INSERT INTO majors (name) VALUES ('Community and Nonprofit Leadership BS');
INSERT INTO majors (name) VALUES ('Computer Engineering BS');
INSERT INTO majors (name) VALUES ('Computer Sciences BA');
INSERT INTO majors (name) VALUES ('Computer Sciences BS');
INSERT INTO majors (name) VALUES ('Computer Sciences Certificate');
INSERT INTO majors (name) VALUES ('Conservation Biology BA');
INSERT INTO majors (name) VALUES ('Conservation Biology BS');
INSERT INTO majors (name) VALUES ('Consulting Certificate');
INSERT INTO majors (name) VALUES ('Consumer Behavior and Marketplace Studies BS');
INSERT INTO majors (name) VALUES ('Consumer Finance and Financial Planning BS');
INSERT INTO majors (name) VALUES ('Consumer Marketplace Studies BS');
INSERT INTO majors (name) VALUES ('Criminal Justice Certificate');
INSERT INTO majors (name) VALUES ('Dairy Science BS');
INSERT INTO majors (name) VALUES ('Dance BS');
INSERT INTO majors (name) VALUES ('Dance BFA');
INSERT INTO majors (name) VALUES ('Dance Certificate');
INSERT INTO majors (name) VALUES ('Dance Studies Certificate');
INSERT INTO majors (name) VALUES ('Data Science BA');
INSERT INTO majors (name) VALUES ('Data Science BS');
INSERT INTO majors (name) VALUES ('Data Science Certificate');
INSERT INTO majors (name) VALUES ('Design Strategy Certificate');
INSERT INTO majors (name) VALUES ('Development Economics Certificate');
INSERT INTO majors (name) VALUES ('Digital Cinema Production Certificate');
INSERT INTO majors (name) VALUES ('Digital Studies Certificate');
INSERT INTO majors (name) VALUES ('Disability Rights and Services Certificate');
INSERT INTO majors (name) VALUES ('East Asian Studies Certificate');
INSERT INTO majors (name) VALUES ('East Central European Languages, Literatures, and Cultures Certificate');
INSERT INTO majors (name) VALUES ('Economic Analytics Certificate');
INSERT INTO majors (name) VALUES ('Economics BA');
INSERT INTO majors (name) VALUES ('Economics BS');
INSERT INTO majors (name) VALUES ('Education and Educational Services Certificate');
INSERT INTO majors (name) VALUES ('Education Studies BS');
INSERT INTO majors (name) VALUES ('Educational Policy Studies Certificate');
INSERT INTO majors (name) VALUES ('Electrical Engineering BS');
INSERT INTO majors (name) VALUES ('Elementary Education BSE');
INSERT INTO majors (name) VALUES ('Engineering for Energy Sustainability Certificate');
INSERT INTO majors (name) VALUES ('Engineering Mechanics BS');
INSERT INTO majors (name) VALUES ('Engineering Physics BS');
INSERT INTO majors (name) VALUES ('Engineering Thermal Energy Systems Certificate');
INSERT INTO majors (name) VALUES ('English BA');
INSERT INTO majors (name) VALUES ('English BS');
INSERT INTO majors (name) VALUES ('Entomology BS');
INSERT INTO majors (name) VALUES ('Entrepreneurship Certificate');
INSERT INTO majors (name) VALUES ('Environmental Engineering BS');
INSERT INTO majors (name) VALUES ('Environmental Sciences (L&S) BA');
INSERT INTO majors (name) VALUES ('Environmental Sciences (CALS) BS');
INSERT INTO majors (name) VALUES ('Environmental Sciences (L&S) BS');
INSERT INTO majors (name) VALUES ('Environmental Studies Certificate');
INSERT INTO majors (name) VALUES ('European Studies Certificate');
INSERT INTO majors (name) VALUES ('Folklore Certificate');
INSERT INTO majors (name) VALUES ('Food Science BS');
INSERT INTO majors (name) VALUES ('Food Systems Certificate');
INSERT INTO majors (name) VALUES ('Forest Science BS');
INSERT INTO majors (name) VALUES ('French BA');
INSERT INTO majors (name) VALUES ('French BS');
INSERT INTO majors (name) VALUES ('French BSE');
INSERT INTO majors (name) VALUES ('French Certificate');
INSERT INTO majors (name) VALUES ('Game Design Certificate');
INSERT INTO majors (name) VALUES ('Gender and Women’s Studies BA');
INSERT INTO majors (name) VALUES ('Gender and Women’s Studies BS');
INSERT INTO majors (name) VALUES ('Gender and Women’s Studies Certificate');
INSERT INTO majors (name) VALUES ('Genetics and Genomics BS');
INSERT INTO majors (name) VALUES ('Geography BA');
INSERT INTO majors (name) VALUES ('Geography BS');
INSERT INTO majors (name) VALUES ('Geological Engineering BS');
INSERT INTO majors (name) VALUES ('Geology and Geophysics BA');
INSERT INTO majors (name) VALUES ('Geology and Geophysics BS');
INSERT INTO majors (name) VALUES ('German BA');
INSERT INTO majors (name) VALUES ('German BS');
INSERT INTO majors (name) VALUES ('German BSE');
INSERT INTO majors (name) VALUES ('German Certificate');
INSERT INTO majors (name) VALUES ('Global Cultures, Languages, and Education Certificate');
INSERT INTO majors (name) VALUES ('Global Health BS');
INSERT INTO majors (name) VALUES ('Global Health Certificate');
INSERT INTO majors (name) VALUES ('Graphic Design Certificate');
INSERT INTO majors (name) VALUES ('Health and the Humanities Certificate');
INSERT INTO majors (name) VALUES ('Health Policy Certificate');
INSERT INTO majors (name) VALUES ('Health Promotion and Health Equity BS');
INSERT INTO majors (name) VALUES ('History BA');
INSERT INTO majors (name) VALUES ('History BS');
INSERT INTO majors (name) VALUES ('History Certificate');
INSERT INTO majors (name) VALUES ('Horticulture BS');
INSERT INTO majors (name) VALUES ('Human Development and Family Studies BS');
INSERT INTO majors (name) VALUES ('Individual Major (L&S) BA');
INSERT INTO majors (name) VALUES ('Individual Major (CALS) BS');
INSERT INTO majors (name) VALUES ('Individual Major (SOHE) BS');
INSERT INTO majors (name) VALUES ('Individual Major (L&S) BS');
INSERT INTO majors (name) VALUES ('Individual Major BSE');
INSERT INTO majors (name) VALUES ('Industrial Engineering BS');
INSERT INTO majors (name) VALUES ('Information Science BA');
INSERT INTO majors (name) VALUES ('Information Science BS');
INSERT INTO majors (name) VALUES ('Integrated Liberal Studies Certificate');
INSERT INTO majors (name) VALUES ('Integrated Studies in Science, Engineering, and Society Certificate');
INSERT INTO majors (name) VALUES ('Interior Architecture BS');
INSERT INTO majors (name) VALUES ('International Development and Education Certificate');
INSERT INTO majors (name) VALUES ('International Engineering Certificate');
INSERT INTO majors (name) VALUES ('International Studies BA');
INSERT INTO majors (name) VALUES ('International Studies BS');
INSERT INTO majors (name) VALUES ('Introductory Studies in Dance/Movement Therapy Certificate');
INSERT INTO majors (name) VALUES ('Italian BA');
INSERT INTO majors (name) VALUES ('Italian BS');
INSERT INTO majors (name) VALUES ('Italian BSE');
INSERT INTO majors (name) VALUES ('Italian Certificate');
INSERT INTO majors (name) VALUES ('Japanese BA');
INSERT INTO majors (name) VALUES ('Japanese BS');
INSERT INTO majors (name) VALUES ('Japanese BSE');
INSERT INTO majors (name) VALUES ('Japanese Professional Communication Certificate');
INSERT INTO majors (name) VALUES ('Jewish Studies BA');
INSERT INTO majors (name) VALUES ('Jewish Studies BS');
INSERT INTO majors (name) VALUES ('Jewish Studies Certificate');
INSERT INTO majors (name) VALUES ('Journalism JBA');
INSERT INTO majors (name) VALUES ('Journalism JBS');
INSERT INTO majors (name) VALUES ('Kinesiology BS');
INSERT INTO majors (name) VALUES ('Landscape and Urban Studies BA');
INSERT INTO majors (name) VALUES ('Landscape and Urban Studies BS');
INSERT INTO majors (name) VALUES ('Landscape Architecture BLA');
INSERT INTO majors (name) VALUES ('Latin BA');
INSERT INTO majors (name) VALUES ('Latin BS');
INSERT INTO majors (name) VALUES ('Latin BSE');
INSERT INTO majors (name) VALUES ('Latin American, Caribbean, and Iberian Studies BA');
INSERT INTO majors (name) VALUES ('Latin American, Caribbean, and Iberian Studies BS');
INSERT INTO majors (name) VALUES ('Legal Studies BA');
INSERT INTO majors (name) VALUES ('Legal Studies BS');
INSERT INTO majors (name) VALUES ('LGBTQ+ Studies Certificate');
INSERT INTO majors (name) VALUES ('Life Sciences Communication BS');
INSERT INTO majors (name) VALUES ('Linguistics BA');
INSERT INTO majors (name) VALUES ('Linguistics BS');
INSERT INTO majors (name) VALUES ('Manufacturing Engineering Certificate');
INSERT INTO majors (name) VALUES ('Material Culture Studies Certificate');
INSERT INTO majors (name) VALUES ('Materials Science and Engineering BS');
INSERT INTO majors (name) VALUES ('Mathematics BA');
INSERT INTO majors (name) VALUES ('Mathematics BS');
INSERT INTO majors (name) VALUES ('Mathematics Certificate');
INSERT INTO majors (name) VALUES ('Mechanical Engineering BS');
INSERT INTO majors (name) VALUES ('Medieval Studies Certificate');
INSERT INTO majors (name) VALUES ('Microbiology (L&S) BA');
INSERT INTO majors (name) VALUES ('Microbiology (CALS) BS');
INSERT INTO majors (name) VALUES ('Microbiology (L&S) BS');
INSERT INTO majors (name) VALUES ('Middle East Studies Certificate');
INSERT INTO majors (name) VALUES ('Molecular and Cell Biology BA');
INSERT INTO majors (name) VALUES ('Molecular and Cell Biology BS');
INSERT INTO majors (name) VALUES ('Music BA');
INSERT INTO majors (name) VALUES ('Music BS');
INSERT INTO majors (name) VALUES ('Music: Education, B.M. ');
INSERT INTO majors (name) VALUES ('Music: Performance, B.M. ');
INSERT INTO majors (name) VALUES ('Naval Science, BNS ');
INSERT INTO majors (name) VALUES ('Neurobiology BA');
INSERT INTO majors (name) VALUES ('Neurobiology BS');
INSERT INTO majors (name) VALUES ('Nuclear Engineering BS');
INSERT INTO majors (name) VALUES ('Nuclear Engineering Materials Certificate');
INSERT INTO majors (name) VALUES ('Nursing, BSN ');
INSERT INTO majors (name) VALUES ('Nursing, BSN (Accelerated) ');
INSERT INTO majors (name) VALUES ('Nursing, BSN (Accelerated) ');
INSERT INTO majors (name) VALUES ('Nutritional Sciences BS');
INSERT INTO majors (name) VALUES ('Nutritional Sciences, Nutrition, and Dietetics BS');
INSERT INTO majors (name) VALUES ('Organic Agriculture Certificate');
INSERT INTO majors (name) VALUES ('Personal Finance BS');
INSERT INTO majors (name) VALUES ('Pharmaceutical Sciences BS');
INSERT INTO majors (name) VALUES ('Pharmacology and Toxicology BS');
INSERT INTO majors (name) VALUES ('Philosophy BA');
INSERT INTO majors (name) VALUES ('Philosophy BS');
INSERT INTO majors (name) VALUES ('Physical Education BS');
INSERT INTO majors (name) VALUES ('Physics BA');
INSERT INTO majors (name) VALUES ('Physics BS');
INSERT INTO majors (name) VALUES ('Physics Certificate');
INSERT INTO majors (name) VALUES ('Pilates Certificate');
INSERT INTO majors (name) VALUES ('Plant Pathology BS');
INSERT INTO majors (name) VALUES ('Polish BA');
INSERT INTO majors (name) VALUES ('Polish BS');
INSERT INTO majors (name) VALUES ('Political Economy, Philosophy, and Politics Certificate');
INSERT INTO majors (name) VALUES ('Political Science Certificate');
INSERT INTO majors (name) VALUES ('Political Science BA');
INSERT INTO majors (name) VALUES ('Political Science BS');
INSERT INTO majors (name) VALUES ('Portuguese BA');
INSERT INTO majors (name) VALUES ('Portuguese BS');
INSERT INTO majors (name) VALUES ('Portuguese BSE');
INSERT INTO majors (name) VALUES ('Preparing to Teach Abroad Certificate');
INSERT INTO majors (name) VALUES ('Promoting Activity for Diverse Abilities Certificate');
INSERT INTO majors (name) VALUES ('Psychology BA');
INSERT INTO majors (name) VALUES ('Psychology BS');
INSERT INTO majors (name) VALUES ('Public Policy Certificate');
INSERT INTO majors (name) VALUES ('Rehabilitation Psychology BS');
INSERT INTO majors (name) VALUES ('Religious Studies BA');
INSERT INTO majors (name) VALUES ('Religious Studies BS');
INSERT INTO majors (name) VALUES ('Religious Studies Certificate');
INSERT INTO majors (name) VALUES ('Russian BA');
INSERT INTO majors (name) VALUES ('Russian BS');
INSERT INTO majors (name) VALUES ('Russian, East European, and Central Asian Studies Certificate');
INSERT INTO majors (name) VALUES ('Scandinavian Studies BA');
INSERT INTO majors (name) VALUES ('Scandinavian Studies BS');
INSERT INTO majors (name) VALUES ('Scandinavian Studies Certificate');
INSERT INTO majors (name) VALUES ('Science Communication Certificate');
INSERT INTO majors (name) VALUES ('Science of Fermented Food and Beverages Certificate');
INSERT INTO majors (name) VALUES ('Social Justice and Education Certificate');
INSERT INTO majors (name) VALUES ('Social Welfare BA');
INSERT INTO majors (name) VALUES ('Social Welfare BS');
INSERT INTO majors (name) VALUES ('Social Work BSW');
INSERT INTO majors (name) VALUES ('Sociology BA');
INSERT INTO majors (name) VALUES ('Sociology BS');
INSERT INTO majors (name) VALUES ('Soil Science BS');
INSERT INTO majors (name) VALUES ('South Asian Studies Certificate');
INSERT INTO majors (name) VALUES ('Southeast Asian Studies Certificate');
INSERT INTO majors (name) VALUES ('Spanish BA');
INSERT INTO majors (name) VALUES ('Spanish BS');
INSERT INTO majors (name) VALUES ('Spanish BSE');
INSERT INTO majors (name) VALUES ('Spanish Studies for Business Students Certificate');
INSERT INTO majors (name) VALUES ('Special Education BSE');
INSERT INTO majors (name) VALUES ('Sports Communication Certificate');
INSERT INTO majors (name) VALUES ('Statistics BA');
INSERT INTO majors (name) VALUES ('Statistics BS');
INSERT INTO majors (name) VALUES ('Summer Business Fundamentals Certificate');
INSERT INTO majors (name) VALUES ('Supply Chain Management Certificate');
INSERT INTO majors (name) VALUES ('Sustainability Certificate');
INSERT INTO majors (name) VALUES ('Teaching English to Speakers of Other Languages Certificate');
INSERT INTO majors (name) VALUES ('Technical Communication Certificate');
INSERT INTO majors (name) VALUES ('Textiles and Design Certificate');
INSERT INTO majors (name) VALUES ('Textiles and Fashion Design BS');
INSERT INTO majors (name) VALUES ('Theatre and Drama BS');
INSERT INTO majors (name) VALUES ('Theatre Certificate');
INSERT INTO majors (name) VALUES ('Wildlife Ecology BS');
INSERT INTO majors (name) VALUES ('Zoology BA');
INSERT INTO majors (name) VALUES ('Zoology BS');